
services:
  backend:
    image: 954086103677.dkr.ecr.us-east-1.amazonaws.com/devops/backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI: mongodb://raouia:raouia@mongo:27017/devops
      

  frontend:
    image: 954086103677.dkr.ecr.us-east-1.amazonaws.com/devops/frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Volume pour les données MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME: raouia
      - MONGO_INITDB_ROOT_PASSWORD: raouia

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: raouia
      ME_CONFIG_MONGODB_ADMINPASSWORD: raouia
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  mongo-data:
